<p style="font-family: Arial; font-size:3em;color:black;"> Lab W2 </p>

Students name in this Group: <br>
Javier Jiménez Cañizares 101371877<br>
Luis Alberto Sosa Quintero 101369283<br>
Ting Fu Kevin Tsai 101031370<br>
Olanrewaju Yusuf 101364202<br>

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([5, 2, 3, 6, 1, 3, 2, 4, 1])
matrix_A = matrix_A.reshape(3, 3)
print(matrix_A)

# A, B and C are identical in doc therefore only showing A

[[5 2 3]
 [6 1 3]
 [2 4 1]]


In [3]:
matrix_D = np.array([4, -7, 4, 5, 6, -1, -4, 2, 5])
matrix_D = matrix_D.reshape(3, 3)

In [4]:
matrix_AD = np.matmul(matrix_A, matrix_D)
matrix_DA = np.matmul(matrix_D, matrix_A)
print("AD:")
print(matrix_AD)
print("DA:")
print(matrix_DA)

AD:
[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
DA:
[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]


Matrix multiplication is not commutative, therefor AD and DA are different.

Find inverse of B:

$$\left(\begin{array}{ccc|ccc}  
5 & 2 & 3 & 1 & 0 & 0\\
6 & 1 & 3 & 0 & 1 & 0\\
2 & 4 & 1 & 0 & 0 & 1
\end{array}\right)
$$

$$\left(\begin{array}{ccc|ccc}  
1 & -1 & 0 & -1 & 1 & 0\\
6 & 1 & 3 & 0 & 1 & 0\\
2 & 4 & 1 & 0 & 0 & 1
\end{array}\right)
$$

$$\left(\begin{array}{ccc|ccc}  
1 & -1 & 0 & -1 & 1 & 0\\
0 & 7 & 3 & 6 & -5 & 0\\
0 & 6 & 1 & 2 & -2 & 1
\end{array}\right)
$$

$$\left(\begin{array}{ccc|ccc}  
1 & -1 & 0 & -1 & 1 & 0\\
0 & 1 & 0 & 0 & -\frac{1}{11} & \frac{3}{11}\\
0 & 6 & 1 & 2 & -2 & 1
\end{array}\right)
$$

$$\left(\begin{array}{ccc|ccc}  
1 & 0 & 0 & -1 & \frac{10}{11} & \frac{3}{11}\\
0 & 1 & 0 & 0 & -\frac{1}{11} & \frac{3}{11}\\
0 & 0 & 1 & 2 & -\frac{16}{11} & -\frac{7}{11}
\end{array}\right)
$$

In [5]:
matrix_B = np.array([5, 2, 3, 6, 1, 3, 2, 4, 1])
matrix_B = matrix_B.reshape(3, 3)
inverse_B = np.linalg.inv(matrix_B)
print(inverse_B)

[[-1.          0.90909091  0.27272727]
 [ 0.         -0.09090909  0.27272727]
 [ 2.         -1.45454545 -0.63636364]]


In [6]:
inverse_D = np.linalg.inv(matrix_D)
matrix_D_invD = np.matmul(matrix_D, inverse_D)
matrix_invD_D = np.matmul(inverse_D, matrix_D)
print("D * D^-1:")
print(matrix_D_invD)
print("D^-1 * D:")
print(matrix_invD_D)

D * D^-1:
[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 1.38777878e-17  1.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17 -8.32667268e-17  1.00000000e+00]]
D^-1 * D:
[[ 1.00000000e+00  2.49800181e-16 -2.77555756e-17]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Due to floating point number percision, D inverse is not the exact value, thus the result of $DD^{-1}$ and $D^{-1}D$ have small residuals in places where it should be 0 in an identity matrix.

<h3>Bag of Words for [college student, airport taxi driver, Toronto art museum, life art, machine learning student]</h3>

In [7]:
import pandas as pd
bag = pd.DataFrame({"college student" : [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    "airport taxi driver" : [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                    "Toronto art museum" : [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                    "life art" : [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
                    "machine learning student" : [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1]})
bag = bag.T
bag.columns = ["college", "student", "airport", "taxi", "driver", "Toronto",
               "art", "museum", "life", "machine", "learning"]
bag

college  student  airport  taxi  driver  Toronto  \
college student                 1        1        0     0       0        0   
airport taxi driver             0        0        1     1       1        0   
Toronto art museum              0        0        0     0       0        1   
life art                        0        0        0     0       0        0   
machine learning student        0        1        0     0       0        0   

                          art  museum  life  machine  learning  
college student             0       0     0        0         0  
airport taxi driver         0       0     0        0         0  
Toronto art museum          1       1     0        0         0  
life art                    1       0     1        0         0  
machine learning student    0       0     0        1         1

IDF("college") $= log(\frac{5}{1}) \approx 0.699$

IDF("art") $= log(\frac{5}{2}) \approx 0.398$ 