<p style="font-family: Arial; font-size:3em;color:black;"> Lab W1 </p>

Students name in this Group: <br>
Javier Jiménez Cañizares 101371877<br>
Luis Alberto Sosa Quintero 101369283<br>
Ting Fu Kevin Tsai 101031370<br>
Olanrewaju Yusuf 101364202<br>

In [1]:
# importing numpy
import numpy as np

In [2]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
arr = np.array([1, 2, 3, 5, 0])
print(arr)

def check_non_zero(x):
    num_zeros = arr.size - np.count_nonzero(arr)
    if num_zeros == 0:
        return "All elements are non-zero."
    else:
        return str(num_zeros) + " element(s) are zero."
    
print(check_non_zero(arr))

[1 2 3 5 0]
1 element(s) are zero.


In [3]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
arr = np.array([3, -1, 3, 7, 2])
print(arr)
print(check_non_zero(arr))

[ 3 -1  3  7  2]
All elements are non-zero.


In [4]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
arr = np.array([0, 0, 0, 0])
print(arr)
print(check_non_zero(arr))

[0 0 0 0]
4 element(s) are zero.


In [5]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
arr = np.array([56, -2, 7], dtype=np.int32)
print(arr)

print("Memory allocated is " + str(arr.nbytes) + " bytes.")

[56 -2  7]
Memory allocated is 12 bytes.


In [6]:
# Create a numpy array with 10 zeros and print the array.
zero_arr = np.zeros(10, dtype=np.int32)
print(zero_arr)
# Create a numpy array with 6 ones and print the array.
one_arr = np.ones(6, dtype=np.int32)
print(one_arr)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
three_arr = np.full(12, 3)
print(three_arr)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [7]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
arr = np.arange(8, 21)
print(arr)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
arr = np.arange(8, 21, 2)
print(arr)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [8]:
getArrInfo = lambda x : "mean: " + str(np.mean(x)) + " max:" + str(np.max(x)) + " min:" + str(np.min(x)) + " std:" + str(np.std(x))

# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr = np.random.normal(2.0, 0.5, 100)
print("100 random - " + getArrInfo(arr))
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr = np.random.normal(2.0, 0.5, 1000)
print("1000 random - " + getArrInfo(arr))
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr = np.random.normal(2.0, 0.5, 1000000)
print("1000000 random - " + getArrInfo(arr))

100 random - mean: 1.9762217251010257 max:2.8627435395598795 min:0.8484170493980676 std:0.4268356923940434
1000 random - mean: 1.9726057221346 max:3.4260928432714604 min:0.33620543197082786 std:0.4847342570068916
1000000 random - mean: 1.9998284237697201 max:4.493130932506279 min:-0.29730794865307875 std:0.5000596878150604


In [9]:
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?

Since mean and std is input as parameters during array creation, the actual mean and std don't differ much regardless of array size. However, min max values get further away from the mean as number of samples increases.